var shader_showcase = {

"categories":
[{"id":1,"name":"Art &amp; Abstract","img":"","desc":""},
{"id":2,"name":"Automata","img":"","desc":"<a target=\"_blank\" href=\"http://en.wikipedia.org/wiki/Automata_theory\">Automata Theory</a> is the study of abstract machines and the computational problems that can be solved using them."},
{"id":3,"name":"Cellular","img":"","desc":""},
{"id":4,"name":"Flags","img":"","desc":""},
{"id":5,"name":"Fractals","img":"","desc":""},
{"id":6,"name":"Game-like","img":"","desc":""},
{"id":13,"name":"Lighting &amp; Normals","img":"","desc":""},
{"id":7,"name":"Other","img":"","desc":""},
{"id":8,"name":"Raymarching &amp; Raytracing","img":"","desc":""},
{"id":9,"name":"Terrain","img":"","desc":""},
{"id":10,"name":"Text","img":"","desc":""},
{"id":14,"name":"Texture-like","img":"","desc":""},
{"id":11,"name":"Tunnels","img":"","desc":""},
{"id":12,"name":"Volumetric","img":"","desc":""}],

"shaders":
[{"e":"91.27","ext":"png","cat":[6],"name":"Carry the Torch","desc":"Likely the first playable game on GLSL Sandbox.\n\nMove your mouse to the yellow start post at the bottom-right.  Get the green flame and carry it slowly and safely to the purple goal post in the upper-right.  If the screen turns blue, you win!!\n"},
{"e":"97.0","ext":"png","cat":[8],"name":"Sea Noise","desc":"By @paulofalcao"},
{"e":"207.3","ext":"png","cat":[2],"name":"Conway's Game of Life","desc":"The classic game plays out in the backbuffer texture, using blue trails to highlight activity."},
{"e":"355.0","ext":"png","cat":[8],"name":"Marble floor with balls","desc":"By @paulofalcao"},
{"e":"380.0","ext":"png","cat":[1],"name":"Blobs","desc":"By @paulofalcao.  This shader is the ancestor of a large number of blob-type gradient shaders."},
{"e":"383.7","ext":"png","cat":[2],"name":"Al's Bugs","desc":"Bugs (in green) hunt for food (in blue)."},
{"e":"395.0","ext":"png","cat":[1],"name":"Fire blobs","desc":""},
{"e":"424.12","ext":"png","cat":[6],"name":"Shader Invaders","desc":""},
{"e":"452.2","ext":"png","cat":[5],"name":"Steer into the fractal","desc":"Use the mouse to guide your decent into the Mandelbrot set.  Your position is stored as two special pixels in the backbuffer.  Note this doesn't seem to work on ANGLE systems, for reasons unknown."},
{"e":"677.0","ext":"png","cat":[3],"name":"Gems","desc":""},
{"e":"1419.0","ext":"png","cat":[8],"name":"Eyeball","desc":""},
{"e":"1464.0","ext":"png","cat":[8],"name":"DomoKun","desc":""},
{"e":"1621.1","ext":"png","cat":[6],"name":"Half-a-Q*bert in GLSL","desc":"Q*bert will follow the mouse.\nJumping off the board will simply move you back to the top.\nThere's no win condition, but you can toggle each tile twice."},
{"e":"2214.0","ext":"png","cat":[8],"name":"Fishy Escher's \"Depth\"","desc":"Inspired by Escher's \"Depth\""},
{"e":"2531.5","ext":"png","cat":[1],"name":"Mouse-controlled Fire","desc":"Trying to make the rendermonkey fire fully procedural, just starting out learning about glsl."},
{"e":"2533.23","ext":"png","cat":[9],"name":"Terrain","desc":""},
{"e":"2755.0","ext":"png","cat":[1],"name":"Laser Lights","desc":""},
{"e":"3142.1","ext":"png","cat":[8,9],"name":"Sand Dunes","desc":""},
{"e":"3530.7","ext":"png","cat":[5,8],"name":"Fractal Spheretracer","desc":"Simple spheretracer by Kabuto\n\nSpheretracing basically starts by placing a sphere at the center of the coordinate system, and then repeatedly increasing the number of spheres by mirroring the spheres across an arbitrarily defined plane.\n\nOf course the number isn't really always doubled since spheres can also get lost if they were on the wrong side of the mirroring plane (since it mirrors one side onto the other one and overwrites what was left there before).\n\nA huge advantage of this process is that it's very easy to raymarch the result. The distance formula never gets a value that's too high.\n"},
{"e":"3780.3","ext":"png","cat":[8],"name":"Stripey cube thing","desc":"by gngbng.\nThis is mostly just a terrible mishmash of stolen code."}]
};
